# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(783, 403)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.slider_vol = QtWidgets.QSlider(self.centralwidget)
        self.slider_vol.setMaximum(15)
        self.slider_vol.setProperty("value", 5)
        self.slider_vol.setOrientation(QtCore.Qt.Horizontal)
        self.slider_vol.setObjectName("slider_vol")
        self.gridLayout.addWidget(self.slider_vol, 5, 3, 1, 1)
        self.slider_spd = QtWidgets.QSlider(self.centralwidget)
        self.slider_spd.setMaximum(15)
        self.slider_spd.setProperty("value", 5)
        self.slider_spd.setOrientation(QtCore.Qt.Horizontal)
        self.slider_spd.setObjectName("slider_spd")
        self.gridLayout.addWidget(self.slider_spd, 3, 3, 1, 1)
        self.lineEdit_code = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_code.setFont(font)
        self.lineEdit_code.setObjectName("lineEdit_code")
        self.gridLayout.addWidget(self.lineEdit_code, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 1, 1, 1)
        self.slider_pit = QtWidgets.QSlider(self.centralwidget)
        self.slider_pit.setMaximum(15)
        self.slider_pit.setProperty("value", 5)
        self.slider_pit.setOrientation(QtCore.Qt.Horizontal)
        self.slider_pit.setObjectName("slider_pit")
        self.gridLayout.addWidget(self.slider_pit, 4, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 2)
        self.v_spd = QtWidgets.QLabel(self.centralwidget)
        self.v_spd.setObjectName("v_spd")
        self.gridLayout.addWidget(self.v_spd, 3, 2, 1, 1)
        self.v_pit = QtWidgets.QLabel(self.centralwidget)
        self.v_pit.setObjectName("v_pit")
        self.gridLayout.addWidget(self.v_pit, 4, 2, 1, 1)
        self.v_vol = QtWidgets.QLabel(self.centralwidget)
        self.v_vol.setObjectName("v_vol")
        self.gridLayout.addWidget(self.v_vol, 5, 2, 1, 1)
        self.lable_vol = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lable_vol.setFont(font)
        self.lable_vol.setObjectName("lable_vol")
        self.gridLayout.addWidget(self.lable_vol, 2, 1, 1, 1)
        self.comboBox_per = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_per.setObjectName("comboBox_per")
        self.gridLayout.addWidget(self.comboBox_per, 2, 2, 1, 2)
        self.out_path = QtWidgets.QLineEdit(self.centralwidget)
        self.out_path.setObjectName("out_path")
        self.gridLayout.addWidget(self.out_path, 0, 0, 1, 4)
        self.btn_gen = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_gen.setFont(font)
        self.btn_gen.setObjectName("btn_gen")
        self.gridLayout.addWidget(self.btn_gen, 6, 2, 1, 2)
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout.addWidget(self.btn_clear, 6, 1, 1, 1)
        self.filelist = QtWidgets.QListWidget(self.centralwidget)
        self.filelist.setMinimumSize(QtCore.QSize(300, 0))
        self.filelist.setObjectName("filelist")
        self.gridLayout.addWidget(self.filelist, 1, 0, 6, 1)
        self.log = QtWidgets.QTextBrowser(self.centralwidget)
        self.log.setObjectName("log")
        self.gridLayout.addWidget(self.log, 8, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_code.setPlaceholderText(_translate("MainWindow", "utf8"))
        self.label_2.setText(_translate("MainWindow", "音调"))
        self.label.setText(_translate("MainWindow", "语速"))
        self.label_3.setText(_translate("MainWindow", "音量"))
        self.label_5.setText(_translate("MainWindow", "文件编码"))
        self.v_spd.setText(_translate("MainWindow", "TextLabel"))
        self.v_pit.setText(_translate("MainWindow", "TextLabel"))
        self.v_vol.setText(_translate("MainWindow", "TextLabel"))
        self.lable_vol.setText(_translate("MainWindow", "音库"))
        self.out_path.setPlaceholderText(_translate("MainWindow", "输出目录"))
        self.btn_gen.setText(_translate("MainWindow", " 生成"))
        self.btn_clear.setText(_translate("MainWindow", "清空"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
